# Site settings
title: Alignak
email: david.durieux@alignak.net
description: > # this means to ignore newlines until "baseurl:"
  integrated monitoring solution
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.alignak.net" # the base hostname & protocol for your site
twitter_username: alignak_monitor
github_username:  Alignak-monitoring

# Build settings
markdown: kramdown
