# Site settings
title: Alignak
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Integrated monitoring solution. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alignak-monitoring.github.io" # the base hostname & protocol for your site
twitter_username: alignak_monitor
github_username:  Alignak-monitoring

# Build settings
markdown: kramdown
